import numpy as np
import scipy.io

"""
fixedga:    固定高斯噪声
randga:     随机高斯噪声
randga_im:  混合噪声
"""

TRAIN_CFG = {
    "fixedga75_a0.2": {
        "epoch": 100,
        "batch_size": 8,
        "learning_rate": 0.001,
        "train_dataset_path": "cave/fixedga75/train.npz",
        "val_dataset_path": "cave/fixedga75/test.npz",
        "log_dir": "saved_models/cave/fixedga75_a0.2",
        "num_of_layers": 17,
        "alpha": 0.2,
    },
    "randga25_a0.2": {
        "epoch": 100,
        "batch_size": 8,
        "learning_rate": 0.001,
        "train_dataset_path": "cave/randga25/train.npz",
        "val_dataset_path": "cave/randga25/test.npz",
        "log_dir": "saved_models/cave/randga25_a0.2",
        "num_of_layers": 17,
        "alpha": 0.2,
    },
    "randga25_a0.0": {
        "epoch": 100,
        "batch_size": 8,
        "learning_rate": 0.001,
        "train_dataset_path": "cave/randga25/train.npz",
        "val_dataset_path": "cave/randga25/test.npz",
        "log_dir": "saved_models/cave/randga25_a0.0",
        "num_of_layers": 17,
        "alpha": 0.0,
    },
    "randga50_a0.2": {
        "epoch": 100,
        "batch_size": 8,
        "learning_rate": 0.001,
        "train_dataset_path": "cave/randga50/train.npz",
        "val_dataset_path": "cave/randga50/test.npz",
        "log_dir": "saved_models/cave/randga50_a0.2",
        "num_of_layers": 17,
        "alpha": 0.2,
    },
    ##############################
    "randga75_im_a0.8": {
        "epoch": 100,
        "batch_size": 8,
        "learning_rate": 0.001,
        "train_dataset_path": "cave/randga75_im/train.npz",
        "val_dataset_path": "cave/randga75_im/test.npz",
        "log_dir": "saved_models/cave/randga75_im_a0.8",
        "num_of_layers": 17,
        "alpha": 0.8,
    }
}

FT_CFG = {
    "fixedga75_a0.2": {
        "epoch": 200,
        "batch_size": 8,
        "learning_rate": 0.0001,
        "scene_id": 0,
        "interval": 3,
        "finetune_dataset_path": "cave/fixedga75/test.npz",
        "test_dataset_path": "cave/fixedga75/test.npz",
        "log_dir": "saved_models/cave/fixedga75_a0.2",
        "pretrain_path": "saved_models/cave/fixedga75_a0.2/pretrained/experiment_0/models/epoch_99",
        "num_of_layers": 17,
        "alpha": 0.2,
    },
    "randga25_a0.2": {
        "epoch": 200,
        "batch_size": 8,
        "learning_rate": 0.00001,
        "scene_id": 0,
        "interval": 3,
        "finetune_dataset_path": "cave/randga25/test.npz",
        "test_dataset_path": "cave/randga25/test.npz",
        "log_dir": "saved_models/cave/randga25_a0.2",
        "pretrain_path": "saved_models/cave/randga25_a0.2/pretrained/experiment_0/models/epoch_99",
        "num_of_layers": 17,
        "alpha": 0.2,
    },
    "randga50_a0.2": {
        "epoch": 200,
        "batch_size": 8,
        "learning_rate": 0.00001,
        "scene_id": 0,
        "interval": 3,
        "finetune_dataset_path": "cave/randga50/test.npz",
        "test_dataset_path": "cave/randga50/test.npz",
        "log_dir": "saved_models/cave/randga50_a0.2",
        "pretrain_path": "saved_models/cave/randga50_a0.2/pretrained/experiment_0/models/epoch_99",
        "num_of_layers": 17,
        "alpha": 0.2,
    },
    "randga25_a0.0": {
        "epoch": 200,
        "batch_size": 8,
        "learning_rate": 0.00001,
        "scene_id": 0,
        "interval": 2,
        "finetune_dataset_path": "cave/randga25/test.npz",
        "test_dataset_path": "cave/randga25/test.npz",
        "log_dir": "saved_models/cave/randga25_a0.0",
        "pretrain_path": "saved_models/cave/randga25_a0.0/pretrained/experiment_0/models/epoch_99",
        "num_of_layers": 17,
        "alpha": 0.0,
    },
    "randga50_a0.0": {
        "epoch": 200,
        "batch_size": 8,
        "learning_rate": 0.00001,
        "scene_id": 0,
        "interval": 3,
        "finetune_dataset_path": "cave/randga50/test.npz",
        "test_dataset_path": "cave/randga50/test.npz",
        "log_dir": "saved_models/cave/randga50_a0.0",
        "pretrain_path": "saved_models/cave/randga50_a0.2/pretrained/experiment_0/models/epoch_99",
        "num_of_layers": 17,
        "alpha": 0.0,
    },
    "randga75_a0.0": {
        "epoch": 200,
        "batch_size": 8,
        "learning_rate": 0.00001,
        "scene_id": 0,
        "interval": 1,
        "finetune_dataset_path": "cave/randga75/test.npz",
        "test_dataset_path": "cave/randga75/test.npz",
        "log_dir": "saved_models/cave/randga75_a0.0",
        "pretrain_path": "saved_models/cave/randga75_a0.2/pretrained/experiment_0/models/epoch_99",
        "num_of_layers": 17,
        "alpha": 0.0,
    },

    ###########################
    "randga75_im_a0.8": {
        "epoch": 200,
        "batch_size": 8,
        "learning_rate": 0.00001,
        "scene_id": 0,
        "interval": 3,
        "finetune_dataset_path": "cave/randga75_im/test.npz",
        "test_dataset_path": "cave/randga75_im/test.npz",
        "log_dir": "saved_models/cave/randga75_im_a0.8",
        "pretrain_path": "saved_models/cave/randga75_im_a0.8/pretrained/experiment_0/models/epoch_99",
        "num_of_layers": 17,
        "alpha": 0.8
    },
}

TEST_CFG = {
    "fixedga75_a0.2_pretrained": {
        "model_path": "saved_models/cave/fixedga75_a0.2/pretrained/experiment_0/models/epoch_99",
        "result_dir": "saved_models/cave/fixedga75_a0.2/pretrained/experiment_0/results_s0",
        "test_dataset_path": "cave/fixedga75/test.npz",
        "num_of_layers": 17,
        "scene_id": 0,
    },
    "fixedga75_a0.2_ft_s0_itv3": {
        "model_path": "saved_models/cave/fixedga75_a0.2/ft_s0_itv3/experiment_0/models/epoch_198",
        "result_dir": "saved_models/cave/fixedga75_a0.2/ft_s0_itv3/experiment_0/results_s0",
        "test_dataset_path": "cave/fixedga75/test.npz",
        "num_of_layers": 17,
        "scene_id": 0,
    },
    "randga25_a0.2_pretrained": {
        "model_path": "saved_models/cave/randga25_a0.2/pretrained/experiment_0/models/epoch_99",
        "result_dir": "saved_models/cave/randga25_a0.2/pretrained/experiment_0/results_s0",
        "test_dataset_path": "cave/randga25/test.npz",
        "num_of_layers": 17,
        "scene_id": 0,
    },
    "randga50_a0.2_pretrained": {
        "model_path": "saved_models/cave/randga50_a0.2/pretrained/experiment_0/models/epoch_99",
        "result_dir": "saved_models/cave/randga50_a0.2/pretrained/experiment_0/results_s0",
        "test_dataset_path": "cave/randga50/test.npz",
        "num_of_layers": 17,
        "scene_id": 0,
    },
    "randga75_a0.2_pretrained": {
        "model_path": "saved_models/cave/randga75_a0.2/pretrained/experiment_0/models/epoch_99",
        "result_dir": "saved_models/cave/randga75_a0.2/pretrained/experiment_0/results_s0",
        "test_dataset_path": "cave/randga75/test.npz",
        "num_of_layers": 17,
        "scene_id": 0,
    },
    "randga75_im_a0.8_pretrained": {
        "model_path": "saved_models/cave/randga75_im_a0.8/pretrained/experiment_0/models/epoch_99",
        "result_dir": "saved_models/cave/randga75_im_a0.8/pretrained/experiment_0/results_s0",
        "test_dataset_path": "cave/randga75_im/test.npz",
        "num_of_layers": 17,
        "scene_id": 0,
    },

    #################################
    "randga25_a0.2_ft_s0_itv3": {
        "model_path": "saved_models/cave/randga25_a0.2/ft_s0_itv3/experiment_0/models/epoch_102",
        "result_dir": "saved_models/cave/randga25_a0.2/ft_s0_itv3/experiment_0/results",
        "test_dataset_path": "cave/randga25/test.npz",
        "num_of_layers": 17,
        "scene_id": 0,
    },
    "randga25_a0.0_ft_s0_itv3": {
        "model_path": "saved_models/cave/randga25_a0.0/ft_s0_itv3/experiment_0/models/epoch_59",
        "result_dir": "saved_models/cave/randga25_a0.0/ft_s0_itv3/experiment_0/results",
        "test_dataset_path": "cave/randga25/test.npz",
        "num_of_layers": 17,
        "scene_id": 0,
    },
    "randga25_a0.0_ft_s0_itv2": {
        "model_path": "saved_models/cave/randga25_a0.0/ft_s0_itv2/experiment_0/models/epoch_126",
        "result_dir": "saved_models/cave/randga25_a0.0/ft_s0_itv2/experiment_0/results",
        "test_dataset_path": "cave/randga25/test.npz",
        "num_of_layers": 17,
        "scene_id": 0,
    },
    "randga50_a0.2_ft_s0_itv3": {
        "model_path": "saved_models/cave/randga50_a0.2/ft_s0_itv3/experiment_0/models/epoch_191",
        "result_dir": "saved_models/cave/randga50_a0.2/ft_s0_itv3/experiment_0/results",
        "test_dataset_path": "cave/randga50/test.npz",
        "num_of_layers": 17,
        "scene_id": 0,
    },
    "randga50_a0.0_ft_s0_itv3": {
        "model_path": "saved_models/cave/randga50_a0.0/ft_s0_itv3/experiment_0/models/epoch_185",
        "result_dir": "saved_models/cave/randga50_a0.0/ft_s0_itv3/experiment_0/results",
        "test_dataset_path": "cave/randga50/test.npz",
        "num_of_layers": 17,
        "scene_id": 0,
    },
    "randga75_a0.2_ft_s0_itv3": {
        "model_path": "saved_models/cave/randga75_a0.2/ft_s0_itv3/experiment_0/models/epoch_112",
        "result_dir": "saved_models/cave/randga75_a0.2/ft_s0_itv3/experiment_0/results",
        "test_dataset_path": "cave/randga75/test.npz",
        "num_of_layers": 17,
        "scene_id": 0,
    },
    "randga75_a0.0_ft_s0_itv3": {
        "model_path": "saved_models/cave/randga75_a0.0/ft_s0_itv3/experiment_0/models/epoch_193",
        "result_dir": "saved_models/cave/randga75_a0.0/ft_s0_itv3/experiment_0/results",
        "test_dataset_path": "cave/randga75/test.npz",
        "num_of_layers": 17,
        "scene_id": 0,
    },
    "randga75_im_a0.8_ft_s0_itv3": {
        "model_path": "saved_models/cave/randga75_im_a0.8/ft_s0_itv3/experiment_0/models/epoch_174",
        "result_dir": "saved_models/cave/randga75_im_a0.8/ft_s0_itv3/experiment_0/results",
        "test_dataset_path": "cave/randga75_im/test.npz",
        "num_of_layers": 17,
        "scene_id": 0,
    },
    "randga75_im_a0.0_ft_s0_itv3": {
        "model_path": "saved_models/cave/randga75_im_a0.0/ft_s0_itv3/experiment_0/models/epoch_198",
        "result_dir": "saved_models/cave/randga75_im_a0.0/ft_s0_itv3/experiment_0/results",
        "test_dataset_path": "cave/randga75_im/test.npz",
        "num_of_layers": 17,
        "scene_id": 0,
    },
    "randga75_im_a0.8_gapt_ft_s0_itv3": {
        "model_path": "saved_models/cave/randga75_im_a0.8_gapt/ft_s0_itv3/experiment_0/models/epoch_194",
        "result_dir": "saved_models/cave/randga75_im_a0.8_gapt/ft_s0_itv3/experiment_0/results",
        "test_dataset_path": "cave/randga75_im/test.npz",
        "num_of_layers": 17,
        "scene_id": 0,
    },
    
    #################################
    "randga25_a0.2_ft_s0_wo_itv3": {
        "model_path": "saved_models/cave/randga25_a0.2/ft_s0_wo_itv3/experiment_0/models/epoch_196",
        "result_dir": "saved_models/cave/randga25_a0.2/ft_s0_wo_itv3/experiment_0/results",
        "test_dataset_path": "cave/randga25/test.npz",
        "num_of_layers": 17,
        "scene_id": 0,
    },
    "randga50_a0.2_ft_s0_wo_itv3": {
        "model_path": "saved_models/cave/randga50_a0.2/ft_s0_wo_itv3/experiment_0/models/epoch_196",
        "result_dir": "saved_models/cave/randga50_a0.2/ft_s0_wo_itv3/experiment_0/results",
        "test_dataset_path": "cave/randga50/test.npz",
        "num_of_layers": 17,
        "scene_id": 0,
    },
    "randga75_a0.2_ft_s0_wo_itv3": {
        "model_path": "saved_models/cave/randga75_a0.2/ft_s0_wo_itv3/experiment_0/models/epoch_189",
        "result_dir": "saved_models/cave/randga75_a0.2/ft_s0_wo_itv3/experiment_0/results",
        "test_dataset_path": "cave/randga75/test.npz",
        "num_of_layers": 17,
        "scene_id": 0,
    },
    "randga75_im_a0.8_ft_s0_wo_itv3": {
        "model_path": "saved_models/cave/randga75_im_a0.8/ft_s0_wo_itv3/experiment_0/models/epoch_180",
        "result_dir": "saved_models/cave/randga75_im_a0.8/ft_s0_wo_itv3/experiment_0/results",
        "test_dataset_path": "cave/randga75_im/test.npz",
        "num_of_layers": 17,
        "scene_id": 0,
    },

    ###########review2###############
    "randga25_review2_ft1_s0_itv2": {
        "model_path": "saved_models/cave/review2/randga25_a0.0/ft1_s0_itv2/experiment_1/models/epoch_173",
        "result_dir": "saved_models/cave/review2/randga25_a0.0/ft1_s0_itv2/experiment_1/results",
        "test_dataset_path": "cave/randga25/test.npz",
        "num_of_layers": 17,
        "scene_id": 0,
    },
    "randga25_review2_ft2_s0_itv2": {
        "model_path": "saved_models/cave/review2/randga25_a0.0/ft2_s0_itv2/experiment_2/models/epoch_180",
        "result_dir": "saved_models/cave/review2/randga25_a0.0/ft2_s0_itv2/experiment_2/results",
        "test_dataset_path": "cave/randga25/test.npz",
        "num_of_layers": 17,
        "scene_id": 0,
    },
    "randga25_review2_ft3_s0_itv2": {
        "model_path": "saved_models/cave/review2/randga25_a0.0/ft3_s0_itv2/experiment_0/models/epoch_122",
        "result_dir": "saved_models/cave/review2/randga25_a0.0/ft3_s0_itv2/experiment_0/results",
        "test_dataset_path": "cave/randga25/test.npz",
        "num_of_layers": 17,
        "scene_id": 0,
    },
    "randga50_review2_ft1_s0_itv2": {
        "model_path": "saved_models/cave/review2/randga50_a0.0/ft1_s0_itv2/experiment_0/models/epoch_148",
        "result_dir": "saved_models/cave/review2/randga50_a0.0/ft1_s0_itv2/experiment_0/results",
        "test_dataset_path": "cave/randga50/test.npz",
        "num_of_layers": 17,
        "scene_id": 0,
    },
    "randga50_review2_ft2_s0_itv2": {
        "model_path": "saved_models/cave/review2/randga50_a0.0/ft2_s0_itv2/experiment_0/models/epoch_178",
        "result_dir": "saved_models/cave/review2/randga50_a0.0/ft2_s0_itv2/experiment_0/results",
        "test_dataset_path": "cave/randga50/test.npz",
        "num_of_layers": 17,
        "scene_id": 0,
    },
    "randga50_review2_ft3_s0_itv2": {
        "model_path": "saved_models/cave/review2/randga50_a0.0/ft2_s0_itv2/experiment_0/models/epoch_178",
        "result_dir": "saved_models/cave/review2/randga50_a0.0/ft2_s0_itv2/experiment_0/results",
        "test_dataset_path": "cave/randga50/test.npz",
        "num_of_layers": 17,
        "scene_id": 0,
    },

}

